name: Update README with Tokei stats

on:
  push:
    paths:
      - 'solutions/**'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download Tokei binary
        run: |
          curl -LO https://github.com/XAMPPRocky/tokei/releases/download/v12.1.2/tokei-x86_64-unknown-linux-gnu.tar.gz
          tar -xzf tokei-x86_64-unknown-linux-gnu.tar.gz
          chmod +x tokei
          sudo mv tokei /usr/local/bin/

      - name: Generate stats
        run: |
          echo '## 📊 Stats' > STATS.md
          echo >> STATS.md
          tokei solutions/ >> STATS.md

      - name: Inject stats into README
        run: |
          awk '/<!--STATS_START-->/{print; system("cat STATS.md"); found=1; next}
               /<!--STATS_END-->/{found=0}
               !found' README.md > README.tmp
          mv README.tmp README.md

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(readme): update stats"
