name: Update README with Tokei stats

on:
  push:
    paths:
      - 'solutions/**'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate stats with Tokei
        id: tokei
        uses: XAMPPRocky/tokei-action@v1
        with:
          args: -o markdown solutions

      - name: Write stats to STATS.md
        run: |
          echo "${{ steps.tokei.outputs.output }}" > STATS.md

      - name: Inject stats into README
        run: |
          awk '/<!--STATS_START-->/{print; system("cat STATS.md"); found=1; next}
               /<!--STATS_END-->/{found=0}
               !found' README.md > README.tmp
          mv README.tmp README.md

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(readme): update tokei stats"
